import { useEffect, useState } from 'react'
import { Pencil, Plus, Power } from 'lucide-react'
import { cambiarEstadoUsuario, getTarifasGestion, getUsuariosGestion, guardarTarifas, guardarUsuario } from '../../api/administracion.js'
import { useRol } from '../../context/RolContext.jsx'
import { Badge } from '../../components/ui/Badge.jsx'
import { Modal } from '../../components/ui/Modal.jsx'
import { Aviso, Boton, Campo, Tarjeta, TituloSeccion, clasesInput } from '../../components/ui/Elementos.jsx'
import { Tabla, Encabezado, Cuerpo, Fila, Celda } from '../../components/ui/Tabla.jsx'

const nuevo={nombre:'',rut:'',correo:'',rol:'regional',region:'13',unidad:'',tipo:'funcionario',afiliado_vigente:true}
const rutas=[['huespedes','afiliado','baja'],['huespedes','afiliado','alta'],['huespedes','afiliado_medica','baja'],['huespedes','afiliado_medica','alta'],['huespedes','externo','baja'],['huespedes','externo','alta'],['veraneo','fija','baja'],['veraneo','fija','alta'],['veraneo','adicional_externo','baja'],['veraneo','adicional_externo','alta']]
const etiqueta=(r)=>`${r[0]==='huespedes'?'Huéspedes':'Veraneo'} · ${r[1].replace('_',' ')} · ${r[2]}`

export function CatalogosAdmin(){
 const {actor}=useRol(); const [tarifas,setTarifas]=useState(null); const [usuarios,setUsuarios]=useState([]); const [editando,setEditando]=useState(null); const [aviso,setAviso]=useState(''); const [error,setError]=useState('')
 const cargar=()=>Promise.all([getTarifasGestion(),getUsuariosGestion()]).then(([t,u])=>{setTarifas(t);setUsuarios(u.items)})
 useEffect(()=>{cargar()},[])
 const valor=(r)=>tarifas[r[0]][r[1]][r[2]]
 const cambia=(r,v)=>setTarifas((t)=>{const n=structuredClone(t);n[r[0]][r[1]][r[2]]=Number(v);return n})
 const salvarTarifas=async()=>{try{await guardarTarifas(tarifas,actor);setAviso('Tarifas y vigencia guardadas. Ya se usan en nuevas simulaciones y reservas.')}catch(e){setError(e.detail||e.message)}}
 const salvarUsuario=async()=>{setError('');if(!editando.nombre||!editando.rut||!editando.correo)return setError('Nombre, RUT y correo son obligatorios.');try{await guardarUsuario(editando,actor);setEditando(null);setAviso('Usuario guardado.');cargar()}catch(e){setError(e.detail||e.message)}}
 const alternar=async(u)=>{try{await cambiarEstadoUsuario(u.id,u.activo===false,actor);setAviso('Estado del usuario actualizado.');cargar()}catch(e){setError(e.detail||e.message)}}
 return <><TituloSeccion titulo="Tarifas, usuarios y roles" descripcion="Configuración persistente con vigencia, trazabilidad y control de estado." />{aviso&&<div className="mb-4"><Aviso tono="verde">{aviso}</Aviso></div>}{error&&!editando&&<div className="mb-4"><Aviso tono="rojo">{error}</Aviso></div>}
 {tarifas&&<Tarjeta className="mb-5 p-5"><h2 className="font-semibold text-verde-900">Tarifas</h2><div className="mt-3 grid gap-3 sm:grid-cols-2"><Campo etiqueta="Vigencia desde"><input type="date" value={tarifas.vigencia.desde} onChange={(e)=>setTarifas({...tarifas,vigencia:{...tarifas.vigencia,desde:e.target.value}})} className={clasesInput}/></Campo><Campo etiqueta="Vigencia hasta"><input type="date" value={tarifas.vigencia.hasta} onChange={(e)=>setTarifas({...tarifas,vigencia:{...tarifas.vigencia,hasta:e.target.value}})} className={clasesInput}/></Campo>{rutas.map((r)=><Campo key={r.join('.')} etiqueta={etiqueta(r)}><input type="number" min="0" value={valor(r)} onChange={(e)=>cambia(r,e.target.value)} className={clasesInput}/></Campo>)}</div><div className="mt-4"><Boton onClick={salvarTarifas}>Guardar tarifas</Boton></div></Tarjeta>}
 <Tarjeta className="p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold text-verde-900">Usuarios y permisos</h2><Boton onClick={()=>{setError('');setEditando({...nuevo})}}><Plus size={16}/>Crear usuario</Boton></div><div className="mt-4"><Tabla><Encabezado columnas={[{clave:'persona',titulo:'Persona'},{clave:'rol',titulo:'Rol'},{clave:'unidad',titulo:'Unidad'},{clave:'estado',titulo:'Estado'},{clave:'acciones',titulo:''}]}/><Cuerpo>{usuarios.map((u)=><Fila key={u.id}><Celda><strong>{u.nombre}</strong><span className="block text-xs text-slate-500">{u.rut} · {u.correo}</span></Celda><Celda>{u.rol}</Celda><Celda>{u.unidad}</Celda><Celda><Badge tono={u.activo===false?'neutro':'verde'}>{u.activo===false?'Inactivo':'Activo'}</Badge></Celda><Celda><div className="flex justify-end gap-2"><Boton variante="secundario" onClick={()=>{setError('');setEditando({...u})}}><Pencil size={14}/>Editar</Boton><Boton variante="neutro" onClick={()=>alternar(u)}><Power size={14}/>{u.activo===false?'Activar':'Desactivar'}</Boton></div></Celda></Fila>)}</Cuerpo></Tabla></div></Tarjeta>
 <Modal abierto={Boolean(editando)} onCerrar={()=>setEditando(null)} titulo={editando?.id?'Editar usuario':'Crear usuario'} pie={<><Boton variante="neutro" onClick={()=>setEditando(null)}>Cancelar</Boton><Boton onClick={salvarUsuario}>Guardar</Boton></>}>{editando&&<div className="space-y-3">{error&&<Aviso tono="rojo">{error}</Aviso>}<Campo etiqueta="Nombre" requerido><input value={editando.nombre} onChange={(e)=>setEditando({...editando,nombre:e.target.value})} className={clasesInput}/></Campo><div className="grid gap-3 sm:grid-cols-2"><Campo etiqueta="RUT" requerido><input value={editando.rut} onChange={(e)=>setEditando({...editando,rut:e.target.value})} className={clasesInput}/></Campo><Campo etiqueta="Correo" requerido><input type="email" value={editando.correo} onChange={(e)=>setEditando({...editando,correo:e.target.value})} className={clasesInput}/></Campo><Campo etiqueta="Rol"><select value={editando.rol} onChange={(e)=>setEditando({...editando,rol:e.target.value})} className={clasesInput}><option value="admin">Administrador</option><option value="central">Oficina Central</option><option value="regional">Encargada regional</option><option value="afiliado">Afiliado</option><option value="no_afiliado">No afiliado</option></select></Campo><Campo etiqueta="Región"><input value={editando.region} onChange={(e)=>setEditando({...editando,region:e.target.value})} className={clasesInput}/></Campo></div><Campo etiqueta="Unidad"><input value={editando.unidad} onChange={(e)=>setEditando({...editando,unidad:e.target.value})} className={clasesInput}/></Campo></div>}</Modal></>
}
