import { useState } from 'react'
import { store, persistir, registrarAuditoria } from '../../api/store.js'
import { usuarios } from '../../fixtures/usuarios.js'
import { useRol } from '../../context/RolContext.jsx'
import { Boton, Campo, StatCard, Tarjeta, TituloSeccion, clasesInput } from '../../components/ui/Elementos.jsx'
import { Building2, CalendarRange, Settings, Users } from 'lucide-react'

const inicial = store.parametros ?? { anticipacion_minima: 2, anticipacion_maxima: 180, desistimiento_sin_cobro: 7, cobro_fuerza_mayor_dias: 1, maximo_adjunto_mb: 2, plazo_resolucion_dias: 5 }
export function ConfiguracionAdmin() {
  const { actor } = useRol(); const [p, setP] = useState(inicial); const [guardado, setGuardado] = useState(false)
  const cambiar = (k) => (e) => setP((x) => ({ ...x, [k]: Number(e.target.value) }))
  const guardar = () => { store.parametros = p; persistir(); registrarAuditoria({ usuario: actor.nombre, perfil: actor.perfil, accion: 'Actualización de parámetros', entidad: 'Configuración general', detalle: JSON.stringify(p) }); setGuardado(true) }
  return <><TituloSeccion titulo="Panel de administración" descripcion="Configuración central de inmuebles, usuarios, tarifas, temporadas y reglas de negocio." />
    <div className="mb-6 grid gap-4 sm:grid-cols-4"><StatCard etiqueta="Inmuebles" valor={store.inmuebles.length} detalle={`${store.inmuebles.filter((i) => i.activo !== false).length} activos`} icono={Building2} /><StatCard etiqueta="Temporadas" valor={store.temporadas.length} detalle="Configuradas" icono={CalendarRange} /><StatCard etiqueta="Usuarios" valor={usuarios.length} detalle="5 perfiles" icono={Users} /><StatCard etiqueta="Auditoría" valor={store.auditoria.length} detalle="Eventos registrados" icono={Settings} /></div>
    <div className="grid gap-5 lg:grid-cols-2"><Tarjeta className="p-5"><h2 className="font-semibold text-verde-900">Parámetros de reserva</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><Campo etiqueta="Anticipación mínima (días)"><input type="number" value={p.anticipacion_minima} onChange={cambiar('anticipacion_minima')} className={clasesInput} /></Campo><Campo etiqueta="Anticipación máxima (días)"><input type="number" value={p.anticipacion_maxima} onChange={cambiar('anticipacion_maxima')} className={clasesInput} /></Campo><Campo etiqueta="Desistimiento sin cobro (días)"><input type="number" value={p.desistimiento_sin_cobro} onChange={cambiar('desistimiento_sin_cobro')} className={clasesInput} /></Campo><Campo etiqueta="Plazo de resolución (días)"><input type="number" value={p.plazo_resolucion_dias} onChange={cambiar('plazo_resolucion_dias')} className={clasesInput} /></Campo><Campo etiqueta="Cobro fuerza mayor (días)"><input type="number" value={p.cobro_fuerza_mayor_dias} onChange={cambiar('cobro_fuerza_mayor_dias')} className={clasesInput} /></Campo><Campo etiqueta="Adjunto máximo (MB)"><input type="number" value={p.maximo_adjunto_mb} onChange={cambiar('maximo_adjunto_mb')} className={clasesInput} /></Campo></div><div className="mt-4 flex items-center gap-3"><Boton onClick={guardar}>Guardar parámetros</Boton>{guardado && <span className="text-sm text-verde-700">Cambios guardados y auditados.</span>}</div></Tarjeta>
    <Tarjeta className="p-5"><h2 className="font-semibold text-verde-900">Módulos administrativos</h2><ul className="mt-3 space-y-3 text-sm text-slate-700"><li><strong>Inmuebles:</strong> ficha, capacidad, equipamiento, fotografías y zonas de interés.</li><li><strong>Tarifas:</strong> vigencia anual, temporada, categorías y vista previa.</li><li><strong>Temporadas:</strong> restricciones, bloqueos, postulación y sorteo.</li><li><strong>Usuarios y roles:</strong> perfiles, región, estado y permisos.</li><li><strong>Nómina:</strong> carga, validaciones, duplicados e historial.</li><li><strong>Auditoría:</strong> cambios de configuración y operaciones.</li></ul></Tarjeta></div>
  </>
}
