import { useCallback, useEffect, useMemo, useState } from 'react'
import { CircleDollarSign, FileWarning, ShieldAlert } from 'lucide-react'
import { getReservas } from '../../api/reservas.js'
import { actualizarCobro, getCobrosGestion, prepararCobros, resolverIncidencia } from '../../api/administracion.js'
import { crearSancion } from '../../api/gestion.js'
import { pesos } from '../../lib/formato.js'
import { useRol } from '../../context/RolContext.jsx'
import { Badge } from '../../components/ui/Badge.jsx'
import { Modal } from '../../components/ui/Modal.jsx'
import { Aviso, Boton, Campo, StatCard, Tarjeta, TituloSeccion, clasesInput } from '../../components/ui/Elementos.jsx'

export function OperacionCentral() {
 const {actor}=useRol();const [reservas,setReservas]=useState([]);const [cobros,setCobros]=useState([]);const [caso,setCaso]=useState(null);const [fundamento,setFundamento]=useState('');const [aviso,setAviso]=useState('');const [error,setError]=useState('')
 const cargar=useCallback(()=>Promise.all([getReservas({}),getCobrosGestion()]).then(([r,c])=>{setReservas(r.items);setCobros(c.items)}),[]);useEffect(()=>{cargar()},[cargar])
 const pendientesFM=reservas.filter((r)=>r.estado==='fuerza_mayor_pendiente');const incidencias=reservas.filter((r)=>r.incidencia&&r.incidencia.estado!=='cerrada'&&r.incidencia.estado!=='sancionada');const total=useMemo(()=>cobros.reduce((s,c)=>s+c.monto,0),[cobros])
 const generar=async()=>{await prepararCobros(actor);setAviso('Cobros recalculados sin duplicar reservas.');cargar()}
 const estadoCobro=async(c,estado)=>{await actualizarCobro(c.id,{estado},actor);setAviso(`Cobro ${c.reserva_codigo} marcado como ${estado}.`);cargar()}
 const resolver=async(decision)=>{setError('');if(!fundamento.trim())return setError('El fundamento es obligatorio.');try{if(decision==='sancionada')await crearSancion({usuario_rut:caso.titular_rut,usuario_nombre:caso.titular_nombre,tipo:'incidencia',etiqueta_tipo:'Incidencia de estadía',motivo:fundamento,desde:new Date().toISOString().slice(0,10),hasta:'2026-12-31'},actor);await resolverIncidencia(caso.codigo,decision,fundamento,actor);setCaso(null);setFundamento('');setAviso('Incidencia resuelta y registrada en auditoría.');cargar()}catch(e){setError(e.detail||e.message)}}
 return <><TituloSeccion titulo="Operación de Oficina Central" descripcion="Prepare y apruebe cobros; cierre incidencias o conviértalas en sanciones con fundamento." acciones={<Boton onClick={generar}>Preparar cobros</Boton>}/>{aviso&&<div className="mb-4"><Aviso tono="verde">{aviso}</Aviso></div>}
 <div className="mb-6 grid gap-4 sm:grid-cols-3"><StatCard etiqueta="Cobros preparados" valor={cobros.length} detalle={pesos(total)} icono={CircleDollarSign}/><StatCard etiqueta="Fuerzas mayores" valor={pendientesFM.length} detalle="Pendientes de resolución" icono={ShieldAlert}/><StatCard etiqueta="Incidencias abiertas" valor={incidencias.length} detalle="Requieren decisión" icono={FileWarning}/></div>{pendientesFM.length>0&&<Aviso tono="ambar">Hay {pendientesFM.length} solicitudes de fuerza mayor pendientes; se excluyen hasta resolverlas.</Aviso>}
 <div className="mt-5 grid gap-5 lg:grid-cols-2"><Tarjeta className="p-5"><h2 className="font-semibold text-verde-900">Cobros</h2>{!cobros.length?<p className="mt-3 text-sm text-slate-500">Use “Preparar cobros” para generar registros.</p>:<ul className="mt-3 divide-y divide-arena-200">{cobros.map((c)=><li key={c.id} className="flex flex-wrap items-center justify-between gap-3 py-3 text-sm"><span><strong>{c.reserva_codigo}</strong><span className="block text-slate-500">{c.titular_nombre}</span></span><span className="text-right"><Badge tono={c.estado==='aprobado'?'verde':'ambar'}>{c.estado}</Badge><strong className="block">{pesos(c.monto)}</strong></span><div className="flex gap-2"><Boton variante="secundario" disabled={c.estado==='aprobado'} onClick={()=>estadoCobro(c,'aprobado')}>Aprobar</Boton><Boton variante="neutro" disabled={c.estado==='observado'} onClick={()=>estadoCobro(c,'observado')}>Observar</Boton></div></li>)}</ul>}</Tarjeta>
 <Tarjeta className="p-5"><h2 className="font-semibold text-verde-900">Incidencias regionales</h2>{!incidencias.length?<p className="mt-3 text-sm text-slate-500">Sin incidencias abiertas.</p>:<ul className="mt-3 divide-y divide-arena-200">{incidencias.map((r)=><li key={r.codigo} className="py-3 text-sm"><strong>{r.codigo} · {r.incidencia.tipo}</strong><p className="text-slate-600">{r.incidencia.descripcion}</p>{r.incidencia.evidencia&&<p className="text-xs text-slate-500">Respaldo: {r.incidencia.evidencia.nombre}</p>}<Boton className="mt-2" variante="secundario" onClick={()=>{setError('');setCaso(r)}}>Resolver caso</Boton></li>)}</ul>}</Tarjeta></div>
 <Modal abierto={Boolean(caso)} onCerrar={()=>setCaso(null)} titulo="Resolver incidencia" descripcion={caso?.codigo} pie={<><Boton variante="neutro" onClick={()=>setCaso(null)}>Cancelar</Boton><Boton variante="secundario" onClick={()=>resolver('cerrada')}>Cerrar sin sanción</Boton><Boton variante="peligro" onClick={()=>resolver('sancionada')}>Crear sanción</Boton></>}>{error&&<Aviso tono="rojo">{error}</Aviso>}<Campo etiqueta="Fundamento de la decisión" requerido className="mt-3"><textarea rows="5" value={fundamento} onChange={(e)=>setFundamento(e.target.value)} className={clasesInput}/></Campo></Modal></>
}
